---
- name: Show hidden files in finder
  osx_defaults:
    domain=com.apple.finder
    key=AppleShowAllFiles
    type=bool
    value=true
    state=present

- name: Set a faster key repeat rate
  osx_defaults: domain=NSGlobalDomain key=KeyRepeat type=int value=0

- name: Set a shorter delay until key repeat
  osx_defaults: domain=NSGlobalDomain key=InitialKeyRepeat type=int value=15

- name: Put dock on right side of screen
  osx_defaults: domain=com.apple.dock key=orientation type=string value=right
  register: dock

- name: restart dock if changed
  shell: killall Dock
  when: dock.changed
