---
- name: Show hidden files in finder
  osx_defaults:
    domain=com.apple.finder
    key=AppleShowAllFiles
    type=bool
    value=true

- name: Set a faster key repeat rate
  osx_defaults: domain=NSGlobalDomain key=KeyRepeat type=int value=1

- name: Set a shorter delay until key repeat
  osx_defaults: domain=NSGlobalDomain key=InitialKeyRepeat type=int value=10

- name: Read custom keys
  command: defaults read com.apple.finder NSUserKeyEquivalents
  changed_when: false
  register: custom_keys

- name: write custom keys
  command: defaults write com.apple.finder NSUserKeyEquivalents -dict "\\033File\\033New Finder Window" "@\$n" "\\033File\\033New Folder" "@n"
  when: "'New Folder' not in custom_keys.stdout or 'New Finder Window' not in custom_keys.stdout"

- name: Change dock settings
  osx_defaults:
    domain=com.apple.dock
    key={{ item.key }}
    type={{ item.type }}
    value={{ item.value }}
  with_items:
    - { key: 'orientation', type: 'string', value: 'right' }
    - { key: 'autohide', type: 'bool', value: 'true' }
  register: dock

- name: restart dock if changed
  shell: killall Dock
  when: dock.changed
