---
- name: Clone Powerline fonts repo
  git:
    clone=true
    repo=https://github.com/powerline/fonts.git
    dest="~/fonts"
    update=no
  register: cloning
 
- name: Install Powerline fonts
  shell: "~/fonts/install.sh"
  when: cloning.changed

- name: Set agnoster theme in zshrc
  lineinfile:
    dest=~/.zshrc
    regexp=^ZSH_THEME=
    line="ZSH_THEME=\"agnoster\""

